<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="55" started-at="2017-08-29T12:34:47Z" finished-at="2017-08-29T12:34:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="55" started-at="2017-08-29T12:34:47Z" finished-at="2017-08-29T12:34:47Z">
      <class name="New.BCP">
        <test-method status="FAIL" signature="f()[pri:0, instance:New.BCP@ae45eb6]" name="f" duration-ms="21" started-at="2017-08-29T18:04:47Z" finished-at="2017-08-29T18:04:47Z">
          <exception class="com.codoid.products.exception.FilloException">
            <message>
              <![CDATA[Workbook is not found - /START/test-output/Excell.xlsx]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.codoid.products.exception.FilloException: Workbook is not found - /START/test-output/Excell.xlsx
	at com.codoid.products.fillo.Fillo.getConnection(Fillo.java:45)
	at New.BCP.f(BCP.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.codoid.products.exception.FilloException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- New.BCP -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
